# Generated by Django 5.1.4 on 2025-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurz', models.CharField(max_length=5)),
                ('linka', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prijezd', models.CharField(max_length=5)),
                ('odjezd', models.CharField(max_length=5)),
                ('kolej', models.CharField(max_length=1)),
            ],
        ),
    ]
